services:
  mysql_db:
    build: ./db
    container_name: mysql_db
    expose:
      - '3306'

  backend:
    build: ./backend
    depends_on:
      - mysql_db
    container_name: backend
    ports:
      - '8080:8080'
    expose:
      - '8080'
  
  frontend:
    build: ./frontend
    depends_on:
      - backend
      - mysql_db
    ports:
      - '3000:3000'
    expose:
      - '3000'