services:
  mysql_db:
    build: ./db
    container_name: mysql_db
    expose:
      - '3306'
    volumes:
      - mysql_volume:/var/lib/mysql

  backend:
    build: ./backend
    depends_on:
      - mysql_db
    container_name: backend
    ports:
      - '9002:9002'
    expose:
      - '9002'
    volumes:
      - backend_volume:/files
  
  frontend:
    build: ./frontend
    depends_on:
      - backend
      - mysql_db
    ports:
      - '3000:3000'
    expose:
      - '3000'

volumes:
  mysql_volume:
  backend_volume:
