server:
  port: 9002
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: springuser
    url: jdbc:mysql://mysql_db:3306/growbiz
    password: spring
  jpa:
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    host: smtp.gmail.com
    username: asdcgrowbiz@gmail.com
    password: mvna jrcg ruoh gvry
    port: 587
  thymeleaf:
    prefix: classpath:/template/
keys:
  stripeAPIKey: <YOUR_STRIPE_API_KEY>
  stripeWebhookSecret: <YOUR_STRIPE_WEBHOOK_SECRET>
  secretKey: <SECRET_KEY>
