server:
  port: 9002
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: springuser
    url: jdbc:mysql://mysql_db:3306/growbiz
    password: spring
  jpa:
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    host: smtp.gmail.com
    username:
    password:
    port: 587
keys:
  stripeAPIKey: sk_test_51OCRCVG3Tid9j8Qj6C2alnlyhR4EDQY2CuV90GnVH8vRygyqlv0Wz88be7LvXgeyhKuXBIRro6ool86SkiPljJF300Osq5gVLr
